#:schema https://www.schemastore.org/cargo.json
[package]
description = "CI message formatter"
name        = "cifmt"
version     = "1.0.0"

authors = ["JP-Ellis <josh@jpellis.me>"]

edition = "2024"

license    = { workspace = true }
readme     = { workspace = true }
repository = { workspace = true }

[dependencies]
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = "=1.4.1"
